default:
  image: gradle:7.4.2-jdk11

services:
  - docker:dind

before_script:
  - chmod +x gradlew

stages:
  - build
  - test
#  - publish

build:
  stage: build
#  before_script:
#    - apt-get update
#    - apt-get install git-all -y
#    - git --version
#    - chmod +x gradlew
  script:
    - ./gradlew build -x test
  only:
    - branches

test:
  stage: test
  script:
    - ./gradlew test
    - echo "test"
  only:
    - branches

#publish:
#  stage: publish
#  before_script:
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#    - eval $(ssh-agent -s)
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#  script:
#    - ./gradlew bootWar
#    - scp -r build/libs root@vps10001.winihost.com:/app/tomcat
#  artifacts:
#    paths:
#      - target/
#  only:
#    - branches