INSERT INTO zone
(id,"version", create_at, create_by, type_zone_id, zone_id, code, designation)
VALUES (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '9'), '13751', 'KOUN-FAO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '15'), '13351', 'GBOGUHE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '16'), '13251', 'DALOA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '50'), '15701', 'SEYDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '49'), '15751', 'BAKO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '3'), '15201', 'DIOULATIEDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '51'), '14051', 'ODIENNE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '2'), '16251', 'SAMATIGUILA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '53'), '14951', 'AYAME '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '1'), '18201', 'GBONNE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '6'), '12301', 'ZOUAN-HOUNIEN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '52'), '14351', 'BOOKO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '14'), '14001', 'BOUNA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '42'), '18001', 'OUME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '22'), '13101', 'DUEKOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '41'), '11551', 'M''BAHIAKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '36'), '17651', 'AGNIBILEKROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '24'), '12951', 'BETTIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '47'), '16151', 'SEGUELON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '39'), '18501', 'TIEMELEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '31'), '10401', 'M''BATTO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '58'), '14251', 'OUANINOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '25'), '10551', 'BLOLEQUIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '27'), '13151', 'GUIGLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '28'), '19401', 'TAI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '45'), '16351', 'GOULIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '86'), '13651', 'DABOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '82'), '13601', 'GRAND-LAHOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '72'), '15401', 'GRAND-BEREBY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '74'), '15601', 'SAN-PEDRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '90'), '17301', 'FERKESSEDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '89'), '17101', 'DIAWALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '56'), '14301', 'BOROTOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '77'), '17701', 'SONGON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '87'), '19001', 'ANYAMA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '61'), '16051', 'TIENKO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '60'), '12901', 'MINIGNAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '67'), '15651', 'SASSANDRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '85'), '17851', 'ALEPE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '65'), '15951', 'GUEYO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '64'), '15301', 'MEAGUI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '68'), '16001', 'GRAND-ZATTRY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '62'), '15451', 'SOUBRE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '57'), '14601', 'KOONAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '91'), '17451', 'BOUNDIALI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '92'), '14701', 'KOLIA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '102'), '14751', 'DIKODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '101'), '14451', 'NIOFOIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '100'), '17501', 'M''BENGUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '137'), '15901', 'DIANRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '133'), '15551', 'SARHALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '134'), '16801', 'TIENINGBOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '144'), '12851', 'ADZOPE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '141'), '19351', 'YAKASSE-ATTOBROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '142'), '10501', 'AZAGUIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '143'), '12451', 'RUBINO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '139'), '17401', 'TOUMODI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '116'), '10751', 'BASSAWA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '112'), '11651', 'BONIEREDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '111'), '11301', 'FOUMBOLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '113'), '10701', 'SATAMA-SOKOURA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '119'), '11601', 'DABAKALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '109'), '17901', 'FRONAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '115'), '11101', 'KATIOLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '120'), '11751', 'TAFIRE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '108'), '11801', 'TORTIYA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '106'), '10201', 'BOUAFLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '104'), '18651', 'KOUMBALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '128'), '16501', 'DJIBROSSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '124'), '16651', 'MORONDO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '125'), '16901', 'KANI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '129'), '16751', 'WOROFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '114'), '11901', 'BEOUMI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '110'), '12051', 'BOUAKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '117'), '18401', 'SAKASSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '213'), '13901', 'KOUASSI-DATEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '321'), '16101', 'KANIASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '208'), '13701', 'SANDEGUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '456'), '18151', 'BODOKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '168'), '12201', 'SIPILOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '176'), '18801', 'FACOBLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '215'), '13851', 'TANDA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '191'), '13801', 'ASSUEFRY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '387'), '19551', 'JACQUEVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '207'), '13951', 'TRANSUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '159'), '19151', 'BANGOLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '273'), '13051', 'ABENGOUROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '278'), '10301', 'KOUASSI KOUASSIKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '451'), '11701', 'SATAMA-SOKORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '286'), '11501', 'OUELLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '180'), '12401', 'KOUIBLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '280'), '18051', 'PRIKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '373'), '15801', 'GRABO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '330'), '15351', 'GRAND-BASSAM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '337'), '14201', 'KORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '340'), '14401', 'GUINTEGUELA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '347'), '14651', 'TOUBA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '360'), '19451', 'GUITRY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '356'), '19201', 'DIVO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '466'), '11951', 'BROBO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '242'), '13301', 'BEDIALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '398'), '18701', 'SIRASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '436'), '11251', 'SINFRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '439'), '11201', 'GOHITAFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '252'), '13401', 'SAIOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '247'), '13451', 'ISSIA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '251'), '15101', 'ADIAKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '283'), '11451', 'DAOUKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '246'), '13501', 'VAVOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '18'), '13201', 'ZOUKOUGBEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '333'), '16201', 'DIABO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '281'), '18301', 'ETTROKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '270'), '13001', 'NIABLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '486'), '12701', 'AGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '325'), '14101', 'MADINANI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '320'), '16301', 'TIEME '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '317'), '14551', 'HIRE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '493'), '12801', 'AFFERY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '495'), '12751', 'AKOUPE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '367'), '14851', 'ZIKISSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '295'), '10351', 'BONGOUANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '369'), '19501', 'LAKOTA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '440'), '19801', 'BONON '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '442'), '11151', 'ZUENOULA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '450'), '12001', 'DJEBONOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '292'), '11401', 'ARRAH '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '298'), '11351', 'ANOUMABA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '304'), '10251', 'BOCANDA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '241'), '18851', 'BUYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '302'), '19851', 'DIMBOKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '422'), '14501', 'GUIEMBE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '397'), '17601', 'KARAKORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '399'), '16601', 'KOMBORODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '425'), '17201', 'NIELLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '107'), '17001', 'OUANGOLODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '423'), '14901', 'TIORONIARADOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '415'), '16551', 'KORHOGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '432'), '17551', 'SINEMATIALI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '470'), '15501', 'MASSALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '374'), '15851', 'TABOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '339'), '15051', 'MAFFERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '343'), '19601', 'ABOISSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '344'), '15151', 'BONOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '331'), '15001', 'TIAPOUM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '426'), '15251', 'KONG'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '169'), '12151', 'BIANKOUMA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '151'), '12251', 'DANANE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '192'), '12551', 'LOGOUALE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '185'), '18951', 'SANGOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '189'), '12351', 'MAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '175'), '19051', 'BIN-HOUYE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '473'), '19301', 'DUALLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '471'), '19251', 'SIFIE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '123'), '16451', 'MANKONO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '472'), '16851', 'SEGUELA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '502'), '10451', 'AGBOVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '392'), '11001', 'SIKENSI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '381'), '13551', 'TAABO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '316'), '12651', 'GUIBEROUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '385'), '18901', 'TIASSALE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '299'), '12601', 'OURAGAHIO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '404'), '19651', 'KASSERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '319'), '18551', 'GAGNOA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '197'), '12501', 'BONDOUKOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '411'), '17351', 'KOUTO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '396'), '17051', 'KANAKONO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '409'), '17151', 'GBON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '403'), '18751', 'TENGRELA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '474'), '18251', 'TIE-N''DIEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '489'), '18451', 'DIDIEVI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '509'), '18101', 'DJEKANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '479'), '12101', 'TIEBISSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '476'), '16951', 'KOKOUMBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '445'), '16701', 'KONGASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '446'), '16401', 'KOUNAHIRI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '229'), '19701', 'DOROPO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '219'), '19751', 'NASSIAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '223'), '14151', 'TEHINI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '459'), '18351', 'BOTRO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '268'), '19101', 'TOULEPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '395'), '17801', 'BINGERVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '11051', 'PORT-BOUET'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10801', 'COCODY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10151', 'MARCORY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10651', 'KOUMASSI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10601', 'ADJAME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10051', 'PLATEAU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10951', 'YOPOUGON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10901', 'ATTECOUBE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10851', 'ABOBO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '382'), '10101', 'TREICHVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '487'), '17751', 'YAMOUSSOUKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '366'), '14801', 'FRESCO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 21,  (select z.id from zone z where z.type_zone_id = 11 and z.code = '313'), '17951', 'DIEGONEFLA')
ON CONFLICT DO NOTHING;