INSERT INTO zone
(id,"version", create_at, create_by, type_zone_id, zone_id, code, designation)
VALUES (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '8', 'PINDA-BOROKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '69'), '9', 'KOUN-FAO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '63'), '13', 'KOUASSIA-NIAGUINI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '21'), '7', 'SEMIEN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '77'), '15', 'GBOGUHE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '77'), '16', 'DALOA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '59'), '17', 'GREGBEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '54'), '50', 'SEYDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '90'), '49', 'BAKO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '90'), '3', 'DIOULATIEDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '90'), '51', 'ODIENNE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '6'), '2', 'SAMATIGUILA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '53', 'AYAME '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '54', 'YAOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '24'), '1', 'GBONNE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '11'), '6', 'ZOUAN-HOUNIEN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '72'), '52', 'BOOKO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '65'), '14', 'BOUNA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '64'), '10', 'NIAMOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '36'), '12', 'TOUGBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '5'), '4', 'SOKORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '75'), '21', 'GBAPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '32'), '42', 'OUME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '75'), '22', 'DUEKOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '52'), '41', 'M''BAHIAKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '34', 'AMELEKIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '33', 'ANIASSUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '93'), '35', 'DUFFREBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '93'), '36', 'AGNIBILEKROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '47'), '24', 'BETTIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '54'), '44', 'GBELEBAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '90'), '48', 'BOUGOUSSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '3'), '47', 'SEGUELON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '79'), '39', 'TIEMELEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '79'), '31', 'M''BATTO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '18'), '40', 'BENGASSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '37', 'BIANOUAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '41'), '38', 'NOE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '81'), '58', 'OUANINOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '31'), '25', 'BLOLEQUIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '80'), '26', 'BEDY-GOAZON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '80'), '27', 'GUIGLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '83'), '29', 'ZAGNE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '83'), '28', 'TAI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '12'), '30', 'MEO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '25'), '45', 'GOULIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '25'), '46', 'MAHANDIANA-SOKOURANI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '43', 'GNAGBODOUGNOA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '89'), '86', 'DABOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '39'), '79', 'BACANDA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '39'), '81', 'EBONOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '39'), '82', 'GRAND-LAHOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '108'), '80', 'ATTOUTOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '40'), '83', 'ABOISSO-COMOE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '40'), '84', 'DANGUIRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '14'), '73', 'DOBA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '14'), '75', 'GABIADJI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '14'), '72', 'GRAND-BEREBY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '14'), '74', 'SAN-PEDRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '13'), '71', 'DJOUROUTOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '17'), '90', 'FERKESSEDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '16'), '95', 'BILIMONO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '16'), '94', 'SIKOLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '8'), '89', 'DIAWALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '8'), '93', 'TOUMOUKORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '72'), '56', 'BOROTOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '68'), '77', 'SONGON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '68'), '87', 'ANYAMA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '5'), '61', 'TIENKO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '5'), '60', 'MINIGNAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '15'), '76', 'GRIHIRI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '15'), '70', 'SAGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '15'), '67', 'SASSANDRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '59', 'DOUGROUPALEGNOA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '40'), '78', 'OGHLWAPO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '40'), '85', 'ALEPE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '95'), '66', 'DABOUYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '95'), '65', 'GUEYO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '86'), '63', 'OUPOYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '86'), '64', 'MEAGUI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '85'), '68', 'GRAND-ZATTRY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '85'), '69', 'OKROUYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '85'), '62', 'SOUBRE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '81'), '57', 'KOONAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '28'), '91', 'BOUNDIALI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '27'), '92', 'KOLIA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '27'), '96', 'SIANHALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '68'), '88', 'BROFODOUME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '202', 'LAOUDI-BA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '26'), '102', 'DIKODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '101', 'NIOFOIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '88'), '100', 'M''BENGUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '71'), '136', 'DIANRA-VILLAGE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '71'), '137', 'DIANRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '23'), '135', 'BOUANDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '23'), '132', 'MARANDALLAH'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '23'), '133', 'SARHALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '23'), '134', 'TIENINGBOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '69'), '214', 'BOAHIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '45'), '144', 'ADZOPE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '42'), '145', 'BIEBY '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '42'), '141', 'YAKASSE-ATTOBROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '45'), '146', 'ANNEPE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '142', 'AZAGUIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '143', 'RUBINO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '84'), '140', 'KPOUEBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '84'), '139', 'TOUMODI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '116', 'BASSAWA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '112', 'BONIEREDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '118', 'TENDENE-BAMBARASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '111', 'FOUMBOLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '113', 'SATAMA-SOKOURA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '119', 'DABAKALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '48'), '109', 'FRONAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '48'), '115', 'KATIOLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '106', 'BOUAFLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '17'), '104', 'KOUMBALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '17'), '105', 'TOGONIERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '24'), '156', 'GOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '29'), '128', 'DJIBROSSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '29'), '126', 'FADIADOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '29'), '124', 'MORONDO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '29'), '125', 'KANI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '10'), '129', 'WOROFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '114', 'BEOUMI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '50'), '110', 'BOUAKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '56'), '117', 'SAKASSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '149', 'GBON-HOUYE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '69'), '213', 'KOUASSI-DATEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '194', 'TAOUDI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '153', 'ZONNEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '69'), '210', 'TANKESSE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '38'), '206', 'DIMANDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '25'), '321', 'KANIASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '38'), '204', 'YOROBODI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '38'), '208', 'SANDEGUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '24'), '164', 'KPATA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '163', 'YAPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '58'), '217', 'DIAMBA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '456', 'BODOKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '1'), '168', 'SIPILOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '11'), '172', 'TEAPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '21'), '176', 'FACOBLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '58'), '215', 'TANDA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '63'), '191', 'ASSUEFRY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '22'), '181', 'OUYABLY-GNONDROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '182', 'SANDOUGOU-SOBA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '38'), '209', 'BANDAKAGNI-TOMORA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '195', 'TABAGNE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '89'), '393', 'LOPOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '193', 'GOUMERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '198', 'SAPLI-SEPINGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '58'), '201', 'TCHEDIO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '200', 'TAGADI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '199', 'YEZIMALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '203', 'SOROBANGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '89'), '394', 'TOUPAH'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '58'), '205', 'AMANVI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '485', 'LOLOBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '39'), '388', 'AHOUANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '69'), '212', 'KOKOMIAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '69'), '211', 'TIENKOIKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '108'), '387', 'JACQUEVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '160', 'DIEOUZON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '161', 'GUINGLO-TAHOUAKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '158', 'ZEO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '63'), '207', 'TRANSUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '165', 'ZOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '157', 'KAHIN-ZARABAON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '60'), '228', 'DANIA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '77'), '238', 'ZAIBO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '77'), '233', 'GONATE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '159', 'BANGOLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '75'), '253', 'BAGOHOUO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '98', 'GOHOUO-ZAGNA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '19'), '244', 'DAPEOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '162', 'BLENIMEOUIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '74'), '130', 'BEOUE-ZIBIAO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '21'), '177', 'GUEZON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '21'), '170', 'TIENY-SEABLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '21'), '178', 'KOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '273', 'ABENGOUROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '22'), '103', 'NIDROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '102'), '289', 'ANDE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '243', 'TAPEGUIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '60'), '245', 'KETRO BASSAM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '290', 'KOUAKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '59'), '230', 'GUESSABO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '287', 'ANANDA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '60'), '237', 'DANANON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '288', 'AKPASSANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '451', 'SATAMA-SOKORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '286', 'OUELLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '22'), '180', 'KOUIBLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '57'), '280', 'PRIKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '498', 'LOVIGUIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '98'), '324', 'GAGORE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '54'), '329', 'SAMANGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '354', 'NEBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '13'), '373', 'GRABO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '100'), '330', 'GRAND-BASSAM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '93'), '257', 'DAME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '72'), '337', 'KORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '82'), '338', 'FOUNGBESSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '82'), '340', 'GUINTEGUELA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '72'), '342', 'MAHANDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '82'), '347', 'TOUBA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '97'), '361', 'LAUZOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '97'), '360', 'GUITRY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '454', 'KONDROBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '98'), '363', 'DJIDJI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '12'), '255', 'NEZOBLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '315', 'YOPOHUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '32', 'GALEBOUO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '356', 'DIVO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '424', 'N''DOUFFOUKANKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '50'), '466', 'BROBO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '48'), '449', 'TIMBE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '39'), '389', 'TOUKOUZOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '77'), '242', 'BEDIALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '56'), '447', 'TOUMODI-SAKASSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '77'), '236', 'GADOUAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '102'), '262', 'ASSIE-KOUMASSI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '234', 'BOGUEDIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '26'), '420', 'BORON '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '232', 'IBOGUHE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '398', 'SIRASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '8'), '429', 'KAOUARA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '405', 'DASSOUNGBOHO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '434', 'KANZRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '34'), '437', 'KOUETINFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '34'), '436', 'SINFRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '439', 'GOHITAFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '441', 'ZAGUIETA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '64'), '138', 'DANOA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '80'), '265', 'NIZAHON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '252', 'SAIOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '247', 'ISSIA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '56'), '453', 'DIBRI-ASRIKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '457', 'SOKALA-SOBARA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '458', 'YAOSSEDOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '60'), '231', 'SEITIFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '294', 'N''GUESSANKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '91'), '251', 'ADIAKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '150', 'DALEU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '97', 'KOUAN-HOULE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '152', 'SEILEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '1'), '167', 'YORODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '59'), '240', 'DOMANGBEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '78'), '503', 'NIEMENE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '9'), '505', 'BAHOUAKAHA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '507', 'N''GANON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '249', 'NAMANE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '284', 'N''GATTAKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '101'), '250', 'NAHIO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '282', 'SAMANZA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '60'), '239', 'BAZRA NATTIS'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '283', 'DAOUKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '60'), '246', 'VAVOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '52'), '279', 'BONGUERA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '59'), '18', 'ZOUKOUGBEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '49'), '463', 'KROFOINSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '37'), '216', 'SOMINASSE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '49'), '333', 'DIABO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '53'), '281', 'ETTROKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '52'), '308', 'KONDOSSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '57'), '293', 'KOFFI-AMONKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '57'), '285', 'ANIANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '57'), '305', 'FAMIENKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '270', 'NIABLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '271', 'YAKASSE-FEYASSE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '272', 'ZARANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '92'), '23', 'EBILASSOKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '49'), '448', 'LANGUIBONOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '36'), '222', 'GOGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '93'), '275', 'AKOBOISSUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '93'), '276', 'TANGUELAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '47'), '277', 'DIAMARAKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '20'), '323', 'FENGOLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '45'), '486', 'AGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '45'), '496', 'ASSIKOI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '20'), '326', 'N''GOLOBLASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '32'), '312', 'GUEPAHOUO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '20'), '325', 'MADINANI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '421', 'BEGBESSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '90'), '320', 'TIEME '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '6'), '328', 'KIMBIRILA-SUD'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '508', 'PAKOUABO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '3'), '327', 'GBONGAHA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '45'), '497', 'YAKASSE-ME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '55', 'DIGNAGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '317', 'HIRE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '46'), '493', 'AFFERY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '46'), '494', 'BECOUEFIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '32'), '297', 'TONLA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '46'), '495', 'AKOUPE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '40'), '390', 'ALLOSSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '98'), '348', 'NIAMBEZARIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '98'), '367', 'ZIKISSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '18'), '303', 'N''ZECREZESSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '50'), '468', 'BOUNDA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '42'), '499', 'ABONGOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '45'), '488', 'BECEDI-BRIGNAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '355', 'DIDOKO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '9'), '407', 'KAGBOLODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '357', 'CHIEPO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '353', 'ZEGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '97'), '359', 'DAIRO-DIDIZO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '97'), '362', 'YOCOBOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '102'), '295', 'BONGOUANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '98'), '368', 'GOUDOUKO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '98'), '369', 'LAKOTA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '440', 'BONON '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '99'), '358', 'OGOUDOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '13'), '370', 'OLODIO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '335', 'ADJOUAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '106'), '438', 'TIBEITA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '34'), '433', 'BAZRE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '99', 'KANOROBA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '34'), '435', 'KONONFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '5', 'IRIEFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '443', 'MAMINIGUI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '444', 'VOUEBOUFLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '431', 'ZANZRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '35'), '442', 'ZUENOULA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '103'), '259', 'KOTOBI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '50'), '450', 'DJEBONOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '103'), '291', 'KREGBE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '103'), '292', 'ARRAH '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '56'), '187', 'AYAOU-SRAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '79'), '298', 'ANOUMABA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '79'), '296', 'ASSAHARA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '85'), '376', 'LILIYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '18'), '304', 'BOCANDA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '62'), '301', 'ABIGUI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '19'), '241', 'BUYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '62'), '309', 'DIANGOKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '62'), '311', 'NOFOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '18'), '267', 'KOUADIOBLEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '469', 'ANANGUIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '62'), '302', 'DIMBOKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '26'), '422', 'GUIEMBE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '397', 'KARAKORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '399', 'KOMBORODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '94'), '306', 'MEKRO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '412', 'KONI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '413', 'KOMBOLOKOURA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '414', 'LATAHA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '8'), '425', 'NIELLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '8'), '107', 'OUANGOLODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '427', 'KIEMOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '506', 'SOHOUO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '423', 'TIORONIARADOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '186', 'ZAGOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '415', 'KORHOGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '87'), '417', 'NAFOUN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '88'), '416', 'BOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '88'), '419', 'KATIALI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '88'), '418', 'KATOGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '9'), '432', 'SINEMATIALI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '14'), '375', 'DOGBO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '10'), '470', 'MASSALA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '13'), '371', 'DJAMANDIOKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '13'), '374', 'TABOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '341', 'ADAOU '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '339', 'MAFERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '44'), '343', 'ABOISSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '91'), '334', 'ASSINIE-MAFIA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '91'), '332', 'ETUEBOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '100'), '336', 'BONGO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '100'), '344', 'BONOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '41'), '269', 'NOUAMOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '41'), '331', 'TIAPOUM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '16'), '426', 'KONG'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '81'), '352', 'GBELO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '16'), '307', 'NAFANA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '24'), '166', 'BLAPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '24'), '155', 'GBANGBEGOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '24'), '169', 'BIANKOUMA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '151', 'DANANE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '188', 'BOGOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '30'), '154', 'MAHAPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '80'), '264', 'KAADE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '192', 'LOGOUALE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '179', 'GBANGBEGOUINE-YATI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '183', 'PODIAGOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '190', 'ZIOGOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '185', 'SANGOUINE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '73'), '189', 'MAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '11'), '171', 'BANNEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '15'), '379', 'LOBAKUYA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '11'), '175', 'BIN-HOUYE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '15'), '380', 'MEDON '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '314', 'BAYOTA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '11'), '174', 'GOULALEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '11'), '173', 'YELLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '10'), '473', 'DUALLA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '10'), '467', 'KAMALO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '10'), '471', 'SIFIE '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '23'), '123', 'MANKONO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '10'), '472', 'SEGUELA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '464', 'CECHI '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '492', 'ATTOBROU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '500', 'GRAND-MORIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '501', 'GUESSIGUIE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '478', 'ORESS-KROBOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '318', 'DOUKOUYO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '502', 'AGBOVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '452', 'ANDO-KEKRENOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '33'), '392', 'SIKENSI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '2'), '383', 'PACOBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '2'), '381', 'TAABO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '4'), '384', 'MOROKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '4'), '248', 'N''DOUCI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '316', 'GUIBEROUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '4'), '385', 'TIASSALE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '299', 'OURAGAHIO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '65'), '225', 'BOUKO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '72'), '345', 'NIOKOSSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '310', 'SERIHIO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '81'), '351', 'GOUEKAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '82'), '346', 'DIOMAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '28'), '406', 'GANAONI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '28'), '404', 'KASSERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '28'), '408', 'SIEMPURGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '319', 'GAGNOA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '65'), '226', 'YOUNDOUO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '11', 'APPIMANDOUM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '196', 'BONDO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '27'), '410', 'BLESSEGUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '64'), '224', 'KALAMON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '70'), '197', 'BONDOUKOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '27'), '411', 'KOUTO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '7'), '400', 'DEBETE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '7'), '396', 'KANAKONO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '27'), '409', 'GBON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '7'), '401', 'PAPARA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '7'), '403', 'TENGRELA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '105'), '491', 'MOLONOU-BLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '105'), '504', 'RAVIART'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '105'), '474', 'TIE-N''DIEKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '67'), '480', 'ABOUDE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '33'), '391', 'GOMON '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '81'), '147', 'SANTA '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '28'), '402', 'BAYA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '105'), '489', 'DIDIEVI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '107'), '509', 'DJEKANOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '105'), '490', 'BOLI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '51'), '274', 'MARABADJASSA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '66'), '481', 'LOMOKANKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '66'), '477', 'MOLONOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '66'), '482', 'YAKPABO-SAKASSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '66'), '479', 'TIEBISSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '84'), '475', 'ANGONDA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '84'), '476', 'KOKUMBO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '61'), '445', 'KONGASSO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '61'), '446', 'KOUNAHIRI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '65'), '227', 'ONDEFIDOUO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '64'), '229', 'DOROPO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '37'), '220', 'BOGOFA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '37'), '219', 'NASSIAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '36'), '223', 'TEHINI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '31'), '261', 'DIBOKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '49'), '459', 'BOTRO '),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '31'), '258', 'TINHOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '31'), '263', 'ZEAGLO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '31'), '260', 'DOKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '12'), '266', 'PEHE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '12'), '254', 'TIOBLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '12'), '268', 'TOULEPLEU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '68'), '395', 'BINGERVILLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '68'), '382', 'ABIDJAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '104'), '483', 'ATTIEGOUAKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '43'), '484', 'KOSSOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '43'), '487', 'YAMOUSSOUKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '76'), '300', 'DAHIEPA-KEHI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '5'), '322', 'KIMBIRILA-NORD'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '50'), '465', 'MAMINI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '96'), '365', 'DAHIRI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '96'), '364', 'GBAGBAM'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '96'), '366', 'FRESCO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '15'), '378', 'DAKPADOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 11,  (select z.id from zone z where z.type_zone_id = 31 and z.code = '32'), '313', 'DIEGONEFLA')
ON CONFLICT DO NOTHING;