INSERT INTO zone
(id,"version", create_at, create_by, type_zone_id, code, designation)
VALUES (nextval('zone_id_seq'),0, now(), 'RDD', 1, '01', 'TCHOLOGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '02', 'WORODOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '03', 'CAVALLY'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '04', 'SAN-PEDRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '05', 'NAWA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '06', 'INDENIE-DJUABLIN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '33', 'N''ZI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '07', 'BAGOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '08', 'FOLON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '09', 'PORO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '10', 'BOUNKANI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '11', 'GONTOUGO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '12', 'BAFING'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '13', 'TONKPI'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '32', 'GUEMON'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '14', 'HAUT-SASSANDRA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '15', 'MARAHOUE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '16', 'MORONOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '17', 'GOH'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '18', 'LOH-DJIBOUA'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '19', 'GBOKLE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '20', 'SUD-COMOE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '21', 'IFFOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '22', 'KABADOUGOU'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '23', 'GRANDS PONTS'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '24', 'ABIDJAN'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '25', 'YAMOUSSOUKRO'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '26', 'BELIER'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '27', 'GBEKE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '28', 'HAMBOL'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '29', 'BERE'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '30', 'LA ME'),
 (nextval('zone_id_seq'),0, now(), 'RDD', 1, '31', 'AGNEBY-TIASSA')
ON CONFLICT DO NOTHING;